name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions ðŸš€
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: git clone https://github.com/benboyd97/WordleBot.git
      - run: cd WordleBot
      - run: git switch dev_branch
      - run: docker run -d -t --name=conda continuumio/miniconda3
      - run: docker build -t conda .
      - run: docker run --rm -ti conda
